import java.util.Scanner;
import java.util.Random;

class starter {
	public static void main(String args[]) {
		// Your code goes below here
		
	Random rand = new Random();
	System.out.println("Here are 20 random numbers with values between 1 and 50:");
	int [] x = new int [20];
	int a = 1 + rand.nextInt(50);
	x[0] = a;
	int b = 1 + rand.nextInt(50);
	x[1] = b;
	int c = 1 + rand.nextInt(50);
	x[2] = c;
	int d = 1 + rand.nextInt(50);
	x[3] = d;
	int e = 1 + rand.nextInt(50);
	x[4] = e;
	int f = 1 + rand.nextInt(50);
	x[5] = f;
	int g = 1 + rand.nextInt(50);
	x[6] = g;
	int h = 1 + rand.nextInt(50);
	x[7] = h;
	int i = 1 + rand.nextInt(50);
	x[8] = i;
	int j = 1 + rand.nextInt(50);
	x[9] = j;
	int k = 1 + rand.nextInt(50);
	x[10] = k;
	int l = 1 + rand.nextInt(50);
	x[11] = l;
	int m = 1 + rand.nextInt(50);
	x[12] = m;
	int n = 1 + rand.nextInt(50);
	x[13] = n;
	int o = 1 + rand.nextInt(50);
	x[14] = o;
	int p = 1 + rand.nextInt(50);
	x[15] = p;
	int q = 1 + rand.nextInt(50);
	x[16] = q;
	int r = 1 + rand.nextInt(50);
	x[17] = r;
	int s = 1 + rand.nextInt(50);
	x[18] = s;
	int t = 1 + rand.nextInt(50);
	x[19] = t;
	System.out.print(x[0]+ ", ");
	System.out.print(x[1]+ ", ");
	System.out.print(x[2]+ ", ");
	System.out.print(x[3]+ ", ");
	System.out.print(x[4]+ ", ");
	System.out.print(x[5]+ ", ");
	System.out.print(x[6]+ ", ");
	System.out.print(x[7]+ ", ");
	System.out.print(x[8]+ ", ");
	System.out.print(x[9]+ ", ");
	System.out.print(x[10]+ ", ");
	System.out.print(x[11]+ ", ");
	System.out.print(x[12]+ ", ");
	System.out.print(x[13]+ ", ");
	System.out.print(x[14]+ ", ");
	System.out.print(x[15]+ ", ");
	System.out.print(x[16]+ ", ");
	System.out.print(x[17]+ ", ");
	System.out.print(x[18]+ ", ");
	System.out.println(x[19]+ " ");
	int [] y = new int [20];
	y[19] = a;
	y[18] = b;
	y[17] = c;
	y[16] = d;
	y[15] = e;
	y[14] = f;
	y[13] = g;
	y[12] = h;
	y[11] = i;
	y[10] = j;
	y[9] = k;
	y[8] = l;
	y[7] = m;
	y[6] = n;
	y[5] = o;
	y[4] = p;
	y[3] = q;
	y[2] = r;
	y[1] = s;
	y[0] = t;
	System.out.println("Here are the numbers in reverse order:");
	System.out.print(y[0]+ ", ");
	System.out.print(y[1]+ ", ");
	System.out.print(y[2]+ ", ");
	System.out.print(y[3]+ ", ");
	System.out.print(y[4]+ ", ");
	System.out.print(y[5]+ ", ");
	System.out.print(y[6]+ ", ");
	System.out.print(y[7]+ ", ");
	System.out.print(y[8]+ ", ");
	System.out.print(y[9]+ ", ");
	System.out.print(y[10]+ ", ");
	System.out.print(y[11]+ ", ");
	System.out.print(y[12]+ ", ");
	System.out.print(y[13]+ ", ");
	System.out.print(y[14]+ ", ");
	System.out.print(y[15]+ ", ");
	System.out.print(y[16]+ ", ");
	System.out.print(y[17]+ ", ");
	System.out.print(y[18]+ ", ");
	System.out.print(y[19]+ " ");
	
	}
}
